number_of_neurons: 100
excitation_type: 'MEXICAN_HAT'
use_normalized_weigths: false
std_dev_excitation_multiplier: deg(5)
std_dev_input: deg(5)
time_between_updates: 1.0
use_global_inhibition: false
global_inhibition: 0.0
normalization_type: 'UTMOST'
imu_topic: 'imu'
activity_filename: 'network_activity.txt'
starting_layer: 4
iterations_to_split: 10
iterations_to_merge: 10
max_number_of_neurons: 128
min_number_of_neurons: 16
