number_of_neurons: 100
excitation_type: 'MEXICAN_HAT'
use_normalized_weigths: true
std_dev_excitation: deg(10)
std_dev_input: deg(10)
time_between_updates: 1.0
use_global_inhibition: false
global_inhibition: 0.0
normalization_type: 'UTMOST'
imu_topic: 'imu'
activity_filename: 'network_activity.txt'
